/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baic_net_api_JniUtils */

#ifndef _Included_com_baic_net_api_JniUtils
#define _Included_com_baic_net_api_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baic_net_api_JniUtils
 * Method:    getResult
 * Signature: (Landroid/content/ContextLjava/lang/StringLjava/lang/String)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baic_net_api_JniUtils_getResult(JNIEnv *, jobject obj,
                                                                   jobject context, jstring openid,
                                                                   jstring target);
JNIEXPORT jstring JNICALL Java_com_baic_net_api_JniUtils_getSign(JNIEnv *, jobject obj,
                                                                   jobject context, jstring openid,
                                                                   jstring target);

jobject getSignature(JNIEnv *env, jobject context);

jstring getCertPrint(JNIEnv *env, jobject signature);

void initKey(JNIEnv *env, jstring context, jstring openid);

jstring encrypt(JNIEnv *env, jobject context, jstring openid, jstring target);
jstring sign(JNIEnv *env, jobject context, jstring openid, jstring target);

jbyteArray jString2JByteArray(JNIEnv *env, jstring target);
jstring JByteArray2JString(JNIEnv *env, jbyteArray target);
jstring joinString(JNIEnv *env, jstring str1, jstring str2);
jstring getMd5(JNIEnv *env, jstring target);
jstring XOR(JNIEnv *env, jstring str1, jstring str2);

#ifdef __cplusplus
}
#endif
#endif
